### ISSUE TITLE
Improve lexical shortlist loading time

### ISSUE THREAD

**Issue by andrenatal** [browsermt/marian-dev#19]
### Bug description
It takes a long time to load the lexicon shortlist in memory when operating in an WASM environment. Just as a comparison, we have benchmarks where it takes 14X longer to start a marian object when we load the shortlist along the model, instead of the the model solo. 

### How to reproduce
* Follow the steps in this page: in order to build a `marian-dev` wasm module: https://github.com/browsermt/bergamot-translator/tree/wasm-integration#bergamot-translator
* Follow the steps in this page to run your test page: https://github.com/browsermt/bergamot-translator/tree/wasm-integration/wasm
* Run the test page and note the time to load the models in the log area
*  Comment the shortlist loading here https://github.com/browsermt/bergamot-translator/blob/wasm-integration/wasm/test_page/bergamot.html#L92-L95 and note how faster it runs.

### Context
Please refer to the discussion here https://github.com/browsermt/bergamot-translator/issues/28#issuecomment-780187832 for more context.

**Comment by kpu** [comment]
Suggested solution.  The LexicalShortlistGenerator class is ripe for optimization. It doesn't use the probabilities after pruning, which happens immediately after load, so it shouldn't keep them after pruning either. Can be flattened to this:
```
std::vector<size_t> word_to_offset_;
std::vector<WordIndex> short_lists_;
```
where [&short_lists_[word_to_offset_[word]], &short_lists_[word_to_offset_[word + 1]]) is a sorted array of word indices in the short list for word. Less formally, we concatenate all the shortlist arrays and find the beginning of a shortlist array with word_to_offset_.

These two fixed-length vectors could be replaced with something memory mapped, with a binary file containing a magic header, the length of both vectors, and the contents of the vectors.  

Since all the shortlists are already sorted, we can take the union in generate using a priority queue to pop the list with the lowest index off each time.

**Comment by qianqianzhu** [comment]
I will work on this issue.

**Comment by kpu** [comment]
@qianqianzhu Great, keep in mind that we also have the goal of loading this from bytes.   So `marian-conv` could take on the additional ability to convert text lexical shortlists to some memory representation.

**Comment by abhi-agg** [comment]
@qianqianzhu This is great 👍

**Comment by andrenatal** [comment]
Is there any progress on this?

**Comment by qianqianzhu** [comment]
Hi, the binary shortlist is almost there. The current work in branch [binary_shortlist](https://github.com/marian-nmt/marian-dev/tree/binary_shortlist). I just need to address a few comments left by @kpu.

**Comment by andrenatal** [comment]
Thanks @qianqianzhu! Do you think we might have it done by the end of the week? We are counting on it for the March 31st deliverable which also coincides with the start of the internal foxfooding program.

**Comment by qianqianzhu** [comment]
Yes.

**Comment by andrenatal** [comment]
Wonderful! Thanks!

**Comment by kpu** [comment]
Closing as resolved
